# AWS Configuration
aws_profile: "default"
role_arn: ""

filters:
  region: "ap-southeast-1"

fetchInstancesDetails: 
  enabled: "yes"  # yes/no - Enable fetching instance details
  input_type: "tags"  # csv/tags - Choose input type
  csv_file: "" # Path to CSV file
  tags:
    "Testing": "termination"
    "terminate": "True"
    "Name": "testing_instances"
    "create": "AMI"
         
  implement_tags: "yes"  # yes/no - Apply new tags
  new_tags:
     "Process": "start"
  output_file: "/home/khushimalhotra/Desktop/Office/cleanUpLifeCycle/fetched_instances.csv"  # CSV to save instance details

stopInstances:
  enabled: "yes"  # yes/no - Enable stopping instances
  input_type: "tags"  # csv/tags - Choose input type
  csv_file: "/home/khushimalhotra/Desktop/Office/cleanUpLifeCycle/fetched_instances.csv"  # Path to CSV file
  tags:
    "Process": "start"
  stop_duration: 0  # Number of days to keep instances stopped
  implement_tags: "yes"  # yes/no - Apply new tags before stopping
  new_tags:
    Status: "stopped"
  create_ami: "yes"  # yes/no - Enable AMI creation
  ami_retention: 30  # Days to retain AMI (0 for no retention)
  post_ami_tags: "yes"  # yes/no - Apply tags after AMI creation
  post_ami_new_tags:
    Backup: "completed"
  output_file: "/home/khushimalhotra/Desktop/Office/cleanUpLifeCycle/fetched_instances.csv"  # CSV to save stopped instance details

terminateInstances:
  terminate: ""  # yes/no - Enable instance termination
  input_type: "tags"  # csv/tags - Choose input type
  csv_file: /home/khushimalhotra/Desktop/Office/cleanUpLifeCycle/fetched_instances.csv""  # Path to CSV file
  tags:
    Backup: "completed"
  implement_tags: ""  # yes/no - Apply tags before termination
  new_tags:
    Termination: "scheduled"
  output_file: "/home/khushimalhotra/Desktop/Office/cleanUpLifeCycle/fetched_instances.csv"  # CSV to save terminated instance details
